### ISSUE TITLE
[Question] How to pass files with github model

### ISSUE THREAD

**Issue by vfdev-5** [trainML/trainml-cli#1]
I'd like to pass local configuration file when create a new job:
```python
trainml_client = TrainML()

job = asyncio.run(
    trainml_client.jobs.create(
        ...
        workers=[
            job_cmd,
        ],
        model=dict(git_uri="..."),
        ...
    )
)
```
Currently, I have to commit and push to the repository every time I modify the config. 

Is it possible to append a local file into model's dict definition, such that it will be put into `/opt/trainml/model` and can be used in `job_cmd` ?

Manual solution could be to serialize the file content into `job_cmd` and create the file on the worker. However, I'm not fan of that approach.

Thanks!

**Comment by akowalsk** [comment]
We have now added the ability to start a job from a local directory structure instead of using a git repository.  You can use this by setting the `source_type` to `local` and the `source_uri` to the root directory of the code project in the model dict definition.  An example is the following:

```
job = await trainml_client.jobs.create(
        name="Training Job with Local Output",
        ....
        model=dict(source_type="local", source_uri="~/path_to_model_code"),
    )

# Jobs using Local Model will wait for you to connect in the "waiting for data/model download" state

await job.wait_for("waiting for data/model download")
attach_task = asyncio.create_task(job.attach())
connect_task = asyncio.create_task(job.connect())
await asyncio.gather(attach_task, connect_task)
```

This way, you can just create a model from any local directory instead of having to figure out how to patch particular files of a specific commit in a git repo.

You can find more details [here](https://docs.trainml.ai/blog/2021/06/28/local-model-integration).

Let me know if you have any other concerns with this approach.
